blank_issues_enabled: false
contact_links:
  - name: Start a discussion
    url: https://github.com/orgs/albertlauncher/discussions/new/choose
    about: Post the link to the discussion in the chats to get more attention. 
  - name: Chat on Discord
    url: https://discord.gg/t8G2EkvRZh
    about: Bridged community chat.
  - name: Chat on Telegram
    url: https://telegram.me/albert_launcher_community
    about: Bridged community chat.
  - name: Chat on on IRC (libera#albertlauncher)
    url: https://web.libera.chat/#albertlauncher
    about: Bridged community chat.
